version: '3.1'
services:
  beammp:
    image: ghcr.io/worty/beammp-server
    container_name: beammp
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./cfg:/app/
    network_mode: "host"
